name: mithzar
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: 1.0.8
  flutter_gen: 5.5.0+1
  flutter_svg: 2.0.10
  gap: 3.0.1
  google_fonts: 6.2.1
  sliver_tools: 0.2.12
  # Routing
  auto_route: 8.2.0
  # State Management
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5 
  # Networking
  dio: 5.4.3
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  # Map
  google_maps_flutter: 2.7.0
  # Storage
  secure_shared_preferences: 0.0.4
  cached_network_image: 3.3.1
  # OpenAPI
  api:
    path: ./api

  # Utils
  # flutter_inappwebview: 6.0.0
  intl: 0.19.0
  path_provider: 2.1.3
  open_file_plus: 3.4.1
  phosphor_flutter: 2.1.0

  #Search
  algolia_helper_flutter: 1.0.0
  algolia_insights: 1.0.0

  # Firebase
  firebase_core: ^3.1.0
  # firebase_messaging: ^15.0.1
  
dependency_overrides:
  meta: 1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 6.5.0
  flutter_lints: 4.0.0
  build_runner: 2.4.10
  flutter_gen_runner: 5.5.0+1
  auto_route_generator: 8.0.0
  riverpod_generator: 2.4.2
  json_serializable: 6.8.0
  freezed: 2.5.3
  custom_lint: 0.6.4
  riverpod_lint: 2.3.12

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/logo/
    - assets/svg/
