name: e_commerce_front_end
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.5
  flutter_gen: ^5.1.0+1
  flutter_svg: 1.1.6
  gap: 2.0.1
  google_fonts: ^3.0.1
  # Routing
  auto_route: 5.0.4
  # State Management
  flutter_riverpod: ^2.1.3
  riverpod_annotation: 1.1.1  
  # Networking
  dio: ^4.0.6
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0
  retrofit: 3.3.1
  dartz: ^0.10.1
  # Storage
  secure_shared_preferences: ^0.0.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: 5.1.0+1
  auto_route_generator: 5.0.3
  retrofit_generator: 4.2.0
  riverpod_generator: 1.1.1
  json_serializable: 6.6.0
  freezed: 2.3.2

flutter_gen:
  output: lib/gen/ 
  line_length: 80 
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/logo/
    - assets/svg/