name: e_commerce_front_end
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.6
  flutter_gen: ^5.3.2
  flutter_svg: 2.0.7
  gap: 3.0.1
  google_fonts: ^6.1.0
  # Routing
  auto_route: 7.8.3
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: 2.1.5
  # Networking
  dio: ^5.3.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  retrofit: 4.0.1
  dartz: ^0.10.1
  # Storage
  secure_shared_preferences: ^0.0.4
  cached_network_image: ^3.3.0
  flutterClient:
    path: ./api
  http_interceptor: ^1.0.2

dependency_overrides:
  http: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  flutter_gen_runner: 5.3.2
  auto_route_generator: 7.3.1
  retrofit_generator: 7.0.8
  riverpod_generator: 2.3.2
  json_serializable: 6.7.1
  freezed: 2.4.2

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/logo/
    - assets/svg/
