analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: true
    implicit-casts: false

  exclude:
    - test/*.dart
  errors:
    deprecated_member_use_from_same_package: ignore
