analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    # implicit-dynamic: true
    # implicit-casts: false
    # implicit_dynamic_parameter: true

  exclude:
    - test/*.dart
  errors:
    deprecated_member_use_from_same_package: ignore
