name: api
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: '^5.2.0'
  freezed_annotation: ^2.4.1
  json_annotation: any

dev_dependencies:
  test: ^1.16.0
  freezed: any
  build_runner: any
  json_serializable: any
